# Generated by Django 5.2.17 on 2026-09-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, help_text='Courier tracking number — shown to the customer on their orders page once set.', max_length=100),
        ),
    ]
